version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: monday_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monday_dashboard
      MYSQL_USER: monday
      MYSQL_PASSWORD: mondaypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 